# Generated by Django 4.1 on 2022-08-30 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='afk.jpg', upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='afk.jpg', upload_to='product_images/'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('destination', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
