# Generated by Django 4.1 on 2022-10-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cart_cartitem_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='charge_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='max_range',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='max_speed',
            field=models.FloatField(default=0),
        ),
    ]
