# Generated by Django 4.1 on 2022-10-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_cart_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_number',
        ),
    ]
