# Generated by Django 4.1 on 2022-10-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_cart_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
    ]
